name: Delete S3 bucket stack on merge 

#trigger event for the github action workflowv to initiate
on:
  pull_request:
    types:
      - closed
    paths:
      - 'cloudformation/**'

permissions:
  pull-requests: write
  contents: read
  id-token: write

jobs:  
 #Cleanup after merge
  cleanup-on-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::149536454128:role/Travelease_OICD
          role-session-name: GithubActionsDelete
          aws-region: ap-south-1

      - name: Delete Test Stack
        run: |
          stack_name=nilaj-pr-test-stack-${{github.event.pull_request.number}}
          aws cloudformation delete-stack --stack-name ${stack_name}