name: Deploy AWS Lambda function

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'

permissions:
  pull-requests: write
  contents: read
  id-token: write

jobs:
  deploy-lambda:

    #Sets up runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      #Sets up python enviroment
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      #Installs any dependencies/packages from the requirements.txt file
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      #Configures AWS Credentials securely
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::149536454128:role/Travelease_OICD
          role-session-name: GithubActionsLambda
          aws-region: ap-south-1

      #Zips Lambda directory and updates lambda function
      - name: Deploy Lambda Function
        run:  |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name test-cicd-lambda --zip-file fileb://lambda.zip